<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net9.0</TargetFrameworks>
    <LangVersion>Latest</LangVersion>
    <OutputPath>..\$(Configuration)\</OutputPath>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Native C# library for the DHT11 and DHT22 sensors</Description>
    <Authors>Daniel M. Porrey, Olof Lagerkvist</Authors>
    <Company>Daniel M. Porrey, Olof Lagerkvist</Company>
    <Copyright>Copyright © 2018-2025</Copyright>
    <PackageVersion>2.0.1</PackageVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Device.Gpio" Version="*" />
  </ItemGroup>

</Project>